---
title: "Index"
---

## Deciding What Test to Run

```{mermaid}
%%| file: mermaid_diagrams/test_choice_flowchart.mmd
```

## Main Tests

- [T-Tests](/ttests.qmd)
- [Linear Regression](/linear_regression.qmd)
- [ANCOVA](/ancova.qmd)
- [ANOVA](/anova.qmd)

## Sub Tests

### Normality

- [Shapiro Wilks](/shapiro_wilks.qmd) - Not done
- [qqPlot](/qqPlot.qmd) - Not done

### Post Hoc

- [Tukey HSD](/tukey_hsd.qmd)
- [Tukey Kramer](/tukey_kramer.qmd)

## Unit 3

- [Multivariate Regression](/multivariate_regression.qmd)
- [Model Selection](/model_selection.md)
- [Variable Importance](/variable_importance.qmd)
- [ANCOVA](/ancova.qmd)
- [Similarities between ANOVA/ANCOVA and Linear Regression](/similarities_between_anovaancova_and_linear_regression.md)
- [Interaction Term](/interaction_term.md)
- [Fixed vs Random Effects](/fixed_vs_random_effects.md)
- [Mixed Models](/mixed_models.md)

## Misc

- [Plots](/plots.qmd)

## TODO

- Answer some questions:
	- [Multivariate Regression](/multivariate_regression.qmd#steps-in-running-a-multivariate-regression) 
		- [ ] In bullet 3, figure out what `use='complete.obs'` does in the
		function.
		- [ ] In bullet 5, explain more about the `vif` function in R.
- Assumptions of each test
	- [x] T-test
		- [x] Data is randomly selected from the population
			- Assume True
		- [x] Observations are independent from each other
			- Assume True
		- [x] Data is normal / sample size is large enough.
			- Shapiro-Wilk normality test
		- [x] Equal variance in response data
			- [x] `var.test` - H_o: Variance is equal
	- [ ] Chi-Square
		- [ ] No assumptions made about the data?
	- [ ] ANOVA/MANOVA
		- [ ] Each level's response variables are normally distributed
			- [ ] Shapiro-Wilk normality test
				- [ ] Null hypothesis - Data is normally distributed
		- [ ] Each level's response data has the same variance
			- LeveneTest
				- H_0 - Variance is equal
		- [ ] Samples must be independent from each other
			- Assume True
	- [ ] Post-hoc tests
		- [ ] TukeyHSD
			- [ ] Same as T-test/ANOVA
			- [ ] Data sets must be of equal length
	- [ ] Linear Regression
		- [ ] Linear relationship between variable
			- [ ] Plot data and look to see if the data is linear
		- [ ] There is constant variance of the errors (error are homescedastic)
			- [ ] `ncvTest` - H_0 - errors are homoscedastic
		- [ ] Error are statistically independent
			- [ ] Plot: x = fitted values, y = residuals (error), line y = 0
			- [ ] Look For patterns
		- [ ] Error are normally distributed
			- [ ] `qqPlot` - Points are within the bounded area.
				- [ ] What do the output numbers mean?
			- [ ] `shapiro.test(residuals)` - H_0 - Variance is equal

